### ISSUE TITLE
about travis and coveralls

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/boilerplates#1]
its very better to give the installation part of coveralls to the travis
```yml
script: "npm run-script test-travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
```
and then just add to scripts

```json
"test-travis": "istanbul cover test.js --report lcovonly"
```
or "coveralls" no matter.
it will improve installation time of the package when develop + it is more clean and simple in package.json

**Comment by tunnckoCore** [comment]
and because of using unix things like `&& cat ./coverage/lcov.info | coveralls` cat and pipe

**Comment by tunnckoCore** [comment]
plus: u dont need it (coveralls) locally, when develop

**Comment by tunnckoCore** [comment]
"once apon a time" i have it in devDeps plus more like jshint and jscs and the installation time was...

**Comment by tunnckoCore** [comment]
it just better practise

**Comment by TimothyGu** [comment]
> it will improve installation time of the package when develop

Oh yes of course it will reduce the installation time by about 3 seconds. So speed. Much fast. Wow.

> "once apon a time" i have it in devDeps plus more like jshint and jscs and the installation time was

How does this have to do with coveralls? We do not use jshint or jscs, and those are huge dependencies.

**Comment by tunnckoCore** [comment]
> We do not use jshint or jscs, and those are huge dependencies.

agreed. I just said that I had them in my package.json template and it was awful.
