### ISSUE TITLE
expected.txt and input.txt

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/boilerplates#2]
I find comparing the expected and output strings directly and avoiding the `readFileSync`'s completely cleans up the test.js source a lot. I can understand the desire to have fixture files, however.

For an example, have a look at [dust's](https://github.com/jstransformers/jstransformer-dust) [test/index.js](https://github.com/jstransformers/jstransformer-dust/blob/master/test/index.js). It's all in one source file, and you don't have to look anywhere else.

**Comment by TimothyGu** [comment]
For most of the testsi find it necessary to use a file to ease comparing. This is especially true for bigger tests like Babel, uglify, and whitespace-sensitive formats like Jade. So, I'd rather keep it here and individual module maintainers can decide if they want it.

**Comment by RobLoach** [comment]
:+1:
